apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
  labels:
    app: pacman
spec:
  selector:
    matchLabels:
      app: pacman
  replicas: 2
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: uzyexe/pacman
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
